apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habit
  namespace: habit
  labels:
    app.kubernetes.io/name: habit
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: habit.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habit
                port:
                  number: 80
